Repository thehyve/delphyne, pull requests merged in 2020-12, with the labels that each got.

#59 Vocab manager
  src/omop_etl_wrapper/_paths.py
  src/omop_etl_wrapper/cdm/vocabularies/__init__.py
  src/omop_etl_wrapper/cdm/vocabularies/vocabularies.py
  src/omop_etl_wrapper/model/custom_vocab/__init__.py
  src/omop_etl_wrapper/model/custom_vocab/base_manager/__init__.py
  src/omop_etl_wrapper/model/custom_vocab/base_manager/base_class_manager.py
  src/omop_etl_wrapper/model/custom_vocab/base_manager/base_concept_manager.py
  src/omop_etl_wrapper/model/custom_vocab/base_manager/base_vocab_manager.py
  src/omop_etl_wrapper/model/custom_vocab/custom_vocab_loader.py
  src/omop_etl_wrapper/model/orm_wrapper.py
  src/omop_etl_wrapper/model/stcm/__init__.py
  src/omop_etl_wrapper/model/stcm/stcm_loader.py
  src/omop_etl_wrapper/model/vocab_manager.py
  src/omop_etl_wrapper/model/vocabulary_loader.py
  src/omop_etl_wrapper/wrapper.py
Labels: STCM, enhancement, refactoring

#72 Create codecov.yml
  .github/codecov.yml
Labels: test

#66 Code mapper
  src/omop_etl_wrapper/model/mapping/__init__.py
  src/omop_etl_wrapper/model/mapping/code_mapper.py
  src/omop_etl_wrapper/util/helper.py
  src/omop_etl_wrapper/wrapper.py
Labels: enhancement

#80 Etl stats updates
  .flake8
  src/omop_etl_wrapper/model/etl_stats/__init__.py
  src/omop_etl_wrapper/model/etl_stats/etl_stats.py
  src/omop_etl_wrapper/model/etl_stats/etl_stats_reporter.py
  src/omop_etl_wrapper/model/orm_wrapper.py
  src/omop_etl_wrapper/model/raw_sql_wrapper.py
  src/omop_etl_wrapper/model/source_data/source_data.py
  src/omop_etl_wrapper/model/stcm/stcm_loader.py
  src/omop_etl_wrapper/wrapper.py
  tests/python/model/source_data/test_source_data.py
  tests/python/model/test_etl_stats.py
Labels: enhancement, refactoring, test

#79 Drop/add all constraints methods
  src/omop_etl_wrapper/cdm/vocabularies/vocabularies.py
  src/omop_etl_wrapper/database/constraints/constraint_manager.py
  tests/python/database/constraints/constraint_sets.py
  tests/python/database/constraints/test_constraints.py
Labels: enhancement
